import type { FormConfig, SelectOption } from '@/Global/types/formConfig'
import { statutActiviteOptions } from '@/simadou/schemas/suiviAvancementContratSchemas'

export function getRecommandationMissionProjetFormConfig(
  personnelOptions: SelectOption[],
  acteurOptions: SelectOption[],
  missionOptions: SelectOption[]
): FormConfig {
  return {
    steps: [
      { step: 1, title: 'Identification' },
      { step: 2, title: 'Détails' },
      { step: 3, title: 'Compléments' },
    ],
    fields: [
      {
        name: 'mission',
        label: 'Mission de supervision',
        type: 'select',
        placeholder: 'Sélectionner une mission',
        required: true,
        options: missionOptions,
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'etat',
        label: 'État',
        type: 'select',
        placeholder: 'Sélectionner un état',
        options: [...statutActiviteOptions],
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'numero',
        label: 'Numéro',
        type: 'text',
        maxLength: 50,
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'ref_no',
        label: 'Réf. n°',
        type: 'text',
        maxLength: 50,
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'date_buttoir',
        label: 'Date butoir',
        type: 'date',
        required: true,
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'type_recommandation',
        label: 'Type',
        type: 'text',
        placeholder: 'Ex: À échéance, Immédiat…',
        maxLength: 100,
        gridCols: 2,
        formStep: 1,
      },
      {
        name: 'recommandation',
        label: 'Recommandation',
        type: 'textarea',
        rows: 3,
        gridCols: 2,
        formStep: 2,
      },
      {
        name: 'observation',
        label: 'Observation',
        type: 'textarea',
        rows: 3,
        gridCols: 2,
        formStep: 2,
      },
      {
        name: 'responsable',
        label: 'Responsable',
        type: 'select',
        placeholder: 'Sélectionner une personne',
        options: personnelOptions,
        gridCols: 2,
        formStep: 2,
      },
      {
        name: 'responsable_interne',
        label: 'Responsable interne',
        type: 'select',
        placeholder: 'Sélectionner une personne',
        options: personnelOptions,
        gridCols: 2,
        formStep: 2,
      },
      {
        name: 'structure',
        label: 'Structure',
        type: 'select',
        placeholder: 'Sélectionner une structure',
        options: acteurOptions,
        gridCols: 2,
        formStep: 2,
      },
      {
        name: 'volet_recommandation',
        label: 'Volet',
        type: 'text',
        maxLength: 200,
        gridCols: 2,
        formStep: 3,
      },
      {
        name: 'rubrique',
        label: 'Rubrique',
        type: 'text',
        maxLength: 200,
        gridCols: 2,
        formStep: 3,
      },
      {
        name: 'rapport',
        label: 'Rapport',
        type: 'file',
        accept: 'application/pdf,image/*,.doc,.docx',
        maxSize: 10,
        helperText: 'PDF, DOC ou DOCX — max. 10 Mo',
        gridCols: 1,
        formStep: 3,
      },
    ],
  }
}
